checkpoint:
  dir: hdfs://192.168.50.37:8020/chk

kafka:
  server: 192.168.50.37:9092
  topic: t-stm
  input:
    groupId: s-21

warehouse:
  path: "hdfs://192.168.50.37:8020/user/hive/warehouse"
  username: "root"
  database: "db_ods15.db"

postgres:
  source:
    url: "jdbc:postgresql://192.168.50.37:5432/fb15_00"
    username: "postgres"
    password: "121019"
    dbId: "00"
  index:
    url: "jdbc:postgresql://192.168.50.37:5432/db_index"
    username: "postgres"
    password: "121019"

job:
  parallelism:
    kafkaSource: 1
    hdfsSink: 1
    indexSink: 1